### ISSUE TITLE
RAM explosion on huge # of inserts

### ISSUE THREAD

**Issue by awalias** [supabase/realtime#125]
I am now killing the realtime service when it chews up to 70% on RAM on an instance,

The process restarts but gets caught in a loop of filling up memory and getting killed (with a 3 second restart wait each time), it would be nice if the application could constrain itself and slowly work through the backlog of events (given it has ~670Mb of RAM to play with on the free tier)

I can reliably reproduce this by [inserting 1 million (small) rows of (id, slug) at once using COPY](https://raw.githubusercontent.com/supabase/benchmarks/master/db/migrations/20201124141199_read_data.sql) (make sure to **not** drop the publication first if you're testing this)

an alternative would be to manage this with swap space on the instance but it would be much nicer to handle this in the application itself

I have a live instance which is currently caught in this boot loop so dm me for access (no idea if it will clear itself after some time)

**Comment by abc3** [comment]
Memory issue can reproduce on the working machine `INSERT INTO users (name) SELECT * FROM generate_series(1, 100000);`
It seems the GC doesn't want itself to clean the heap, only can be done after the manual call `:erlang.garbage_collect(pid)`. It may be because `txn` are passed synchronously to all functions, this influences throughput too.

<img width="676" alt="Screenshot 2021-02-16 at 13 34 41" src="https://user-images.githubusercontent.com/1172600/108057762-ba9b3200-705b-11eb-846a-c47486aadf0b.png">

I will try later to check async callings.

**Comment by fracek** [comment]
Agree with @abc3. If switching to async doesn't work, we may need to add backpressure between replication and the rest of the system.

**Comment by abc3** [comment]
Sync calls don't fault. Looks like messages from DB coming too fast and passing to WebSockets too slow, so they accumulate in VM and eat all free RAM.

**Comment by fracek** [comment]
So the only way to solve this is slow down reading from the DB if the changes start accumulating downstream (e.g. WebSockets?)

**Comment by abc3** [comment]
During slow down, the messages will accumulate in epgsql process.
Maybe it can be done with logging in the DETS, then reading with some defined RPS for each export (websocket/connectors).

I think it will be useful for RAM optimization to add a memory handler to managing signals like system_memory_high_watermark, send inactive processes with hard work (Replication/SubscribersNotification) to hibernate mode.

**Comment by w3b6x9** [comment]
@abc3 thanks for looking into this! It could be interesting if we used a memory supervisor ([memsup](http://erlang.org/doc/man/memsup.html)) and like you mentioned have it set the `system_memory_high_watermark` alarm. Then, we'll have to find a way to hibernate (perhaps [:sys.suspend](http://erlang.org/doc//man/sys.html#suspend-1)/[:sys.resume](http://erlang.org/doc//man/sys.html#resume-1) but I'm unfamiliar with their side effects) specific process(es).

**Comment by w3b6x9** [comment]
In the meantime, I investigated the codebase and found some areas where we can refactor to cut down memory usage:

- We're not checking to see if [%Configuration{}](https://github.com/supabase/realtime/blob/master/server/lib/realtime/configuration.ex#L10) contains any webhooks config prior to passing all txn changes to [Connectors.notify](https://github.com/supabase/realtime/blob/master/server/lib/realtime/subscribers_notification.ex#L145) which passes the txn changes to [WebhookConnector.notify](https://github.com/supabase/realtime/blob/master/server/lib/realtime/webhook_connector.ex). Both `Connectors` and `WebhookConnector` are processes so they use up a lot of memory when receiving messages with a lot of txn changes. When I did a check in [SubscribersNotification.handle_call({:notify...)](https://github.com/supabase/realtime/blob/master/server/lib/realtime/subscribers_notification.ex#L22) in my testing, memory usage reduced by ~47% (See 2nd run for details).
- When I was working on my last PR, I noticed that there was a lot of duplicate data stored in `Replication` state txn changes. For example in a transaction with many inserts `%NewRecord{}` stores `type`, `schema`, `table`, `columns`, `record`, and `commit_timestamp`. However, only `record` ever changes between `%NewRecord{}`s. `type` is "INSERT", `schema`, `table`, and `columns` all come from `%Relation{}`, and `commit_timestamp` was already set in `%Begin{}`. I did a test where I didn't set `columns` in `%NewRecord{}` when `Replication` was processing messages, but passed columns to `SubscribersNotification` and set it there right before changes were broadcast. This reduced memory usage by ~17% (See 3rd run for details). However, this gets trickier when we send txn to connectors (e.g. webhooks) and will require slightly more refactoring.
- I found that `SubscribersNotification`, `Connectors`, and `WebhookConnector` `GenServer`s are unnecessary. All three processes block `Replication` from moving on to the next message in its mailbox b/c all the messages sent to those processes are with `GenServer.call` and they need to reply to `Replication` before it can `acknowledge_lsn`. Not only are they blocking `Replication` but also they receive txn changes in their mailboxes, which means each process uses up a lot of memory. As it currently stands, I can't think of any good reasons why they should be processes. When I ran this test and demoted those three `GenServer`s to regular modules, I saw a memory usage reduction of ~80% (See 4th run for details). I did a run with 1 million rows and total memory usage came out to 372MB. This means that by stripping those modules of their `GenServer`s inserting 1 million rows shouldn't be a problem on the free tier.

#### Realtime Startup:

- Total memory: 44MB

<img width="174" alt="Screen Shot 2021-02-18 at 5 03 03 PM" src="https://user-images.githubusercontent.com/5532241/108427671-89616400-720b-11eb-85e1-c2a0c6c15b70.png">

<img width="652" alt="Screen Shot 2021-02-18 at 5 03 21 PM" src="https://user-images.githubusercontent.com/5532241/108427681-8c5c5480-720b-11eb-88f1-fba3f6dd0778.png">

### *All runs are with 100,000 rows of (id, slug) inserted at once using `COPY`

#### 1st Run on `master` branch (no changes):

- Total memory: 413MB

<img width="184" alt="Screen Shot 2021-02-18 at 5 04 44 PM" src="https://user-images.githubusercontent.com/5532241/108427719-99794380-720b-11eb-88c4-0aa57fb57b46.png">

<img width="650" alt="Screen Shot 2021-02-18 at 5 05 11 PM" src="https://user-images.githubusercontent.com/5532241/108427730-9bdb9d80-720b-11eb-9eaa-385c44c0bcf6.png">

#### 2nd Run with configs (`:realtime` configs but no `:webhooks` configs) check:

- Total memory: 218MB (down from 413MB from 1st run)

<img width="183" alt="Screen Shot 2021-02-18 at 5 43 49 PM" src="https://user-images.githubusercontent.com/5532241/108431548-0216ef00-7211-11eb-9d2b-f6acf9050487.png">

<img width="656" alt="Screen Shot 2021-02-18 at 5 43 58 PM" src="https://user-images.githubusercontent.com/5532241/108431566-093dfd00-7211-11eb-8397-95c16e6eb365.png">

#### 3rd Run with configs (`:realtime` and `:webhooks`) check AND adding columns to txn change in `SubscribersNotification` instead of `Replication`:

- Total memory: 180MB (down from 218MB from 2nd run)

<img width="186" alt="Screen Shot 2021-02-18 at 6 03 28 PM" src="https://user-images.githubusercontent.com/5532241/108433273-b580e300-7213-11eb-90fe-fe10f4474749.png">

<img width="654" alt="Screen Shot 2021-02-18 at 6 03 21 PM" src="https://user-images.githubusercontent.com/5532241/108433261-b0239880-7213-11eb-9e7b-6abc29320b14.png">

#### 4th Run on `master` branch but with `SubscribersNotification`, `Connectors`, and `WebhookConnector` as regular modules (stripped of their `GenServer`s):

- Total memory: 85MB (down from 413MB from 1st run)

<img width="177" alt="Screen Shot 2021-02-18 at 6 26 34 PM" src="https://user-images.githubusercontent.com/5532241/108435200-fb8b7600-7216-11eb-87d8-c20b8d92171f.png">

<img width="649" alt="Screen Shot 2021-02-18 at 6 26 45 PM" src="https://user-images.githubusercontent.com/5532241/108435210-ff1efd00-7216-11eb-8c84-c136c93c1f12.png">

### *Last run with 1 million rows of (id, slug) inserted at once using COPY

#### 5th Run on `master` branch but with `SubscribersNotification`, `Connectors`, and `WebhookConnector` as regular modules (stripped of their `GenServer`s):

- Total memory: 372MB

<img width="169" alt="Screen Shot 2021-02-18 at 9 12 09 PM" src="https://user-images.githubusercontent.com/5532241/108447607-2e8d3400-722e-11eb-9e4a-5b0e9044a6ab.png">

<img width="652" alt="Screen Shot 2021-02-18 at 9 12 19 PM" src="https://user-images.githubusercontent.com/5532241/108447627-34831500-722e-11eb-9e03-2eb6499fabd6.png">

**Comment by abc3** [comment]
@w3b6x9 nice places for refactoring!

As I konow, There are several methods to reduce memory by the process - stop it, hibernate, or call GC. 

Suspending is different from hibernation because the process can't communicate with others, only with the system. 
GenServer may go to hibernation mode by the response {:repluy, :ok, :hibernate} / {:noreply, :hibernate}/...

During critical situations when RAM is almost full, it's useful to try to clear all VM `for pid <- Process.list, do: :erlang.garbage_collect(pid)`

Btw, @w3b6x9 could you reproduce this bug? https://github.com/supabase/realtime-js/issues/77
if yes it means the js client can't handle massive messages despite any optimization.

**Comment by abc3** [comment]
Are there any updates here? 
I see @w3b6x9  worked on "mem-usage" brunch, but it didn't merge to the master. 
@w3b6x9 if you have to stop work on this issue, I could try to solve it.

**Comment by w3b6x9** [comment]
@abc3 thanks for following up!

The work I did on [mem-usage](https://github.com/supabase/realtime/tree/mem-usage) is wrapped up in PR #131 and I was waiting on maintainers of the other `realtime` clients to add in binary decoding support. Only `realtime-js` supports receiving binary messages from `realtime` server right now (see: https://github.com/supabase/realtime-js/commit/242fc7dd3c550041a2cbc4ccc0ec06fd416aa82a).

However, we are actively discussing a couple of things in the works related to `realtime`, including [workflows](https://github.com/supabase/realtime/tree/workflows), so the changes I made in `mem-usage` could all be for naught.

With that being said, if you discover any other areas that could alleviate existing/potential memory issues then please let us know and we can discuss. Appreciate it!

**Comment by abc3** [comment]
Thanks, I understood,

I will look closer at your branch and try to find more solutions with the micro instance.
I'll be in touch!

**Comment by abc3** [comment]
Just to be clear, which exactly ec2 instance do you using? How many RAM / CPUs?

**Comment by w3b6x9** [comment]
@abc3 

> which exactly ec2 instance do you using?

Supabase uses t4g instances and the original issue was observed on a `micro` instance.

> How many RAM / CPUs?

1 GiB / 2 vCPU

Keeping in mind that `realtime` service is killed when it "chews up to 70% on RAM on an instance".

**Comment by abc3** [comment]
So...I managed to send a long transaction with 1M rows to one listener through WebSocket. 

Environment:
- t4g.micro instance
- Ubuntu 20.04.2 LTS
- Erlang/OTP 23; Elixir 1.11.2

Procesing tranaction to disc:
<img width="516" alt="Screenshot 2021-05-07 at 11 25 22" src="https://user-images.githubusercontent.com/1172600/117445146-0b2b7880-af43-11eb-8c6b-323b1bf27b1d.png">

Sending db changes:
<img width="519" alt="Screenshot 2021-05-07 at 12 26 23" src="https://user-images.githubusercontent.com/1172600/117445286-2f875500-af43-11eb-88bc-89a2373ad3be.png">


The main things I've done are stored changes on disk and slowed down sending messages in `notify_subscribers` to 4k per second. Based on that, I saw fundamental places for updating business logic.

First of all, avoid passive broadcasting because there is a risk of overfilling the message box. For example, if you start to send messages with a constant speed of 4k per second, a WebSocket consumer with a connection speed of 100 Mbps will handle it normally. In comparison, a consumer with 0.1 Mbps will start overfilling cowboy's message box. In the current implementation, the `handle_realtime_transaction` sends messages to processes at the maximum possible speed, what ok for a short time of events but is a big problem for frequent or large transactions because it's wasting CPU cores and memory when the message box is overflowed. Now you can see the degradation of performance even on sending 10-20k messages.

A new transaction should start a new instance of the `Replication`, and the process should shut down when the transaction is processed. It helps avoid sticking when already having a new transaction but still handling the previous; and references to large binaries.

And of course, needs to move storing changes in `Replication` from process state to disc, because all events of transaction storing directly in the process. Btw, the backlog file was 719MB.

**Comment by w3b6x9** [comment]
@abc3

> I managed to send a long transaction with 1M rows to one listener through WebSocket.

That's absolutely incredible!

> The main things I've done are stored changes on disk

Wanted to link your PR: https://github.com/supabase/realtime/pull/147

Really appreciate you continuing to look into this and putting up a PR! Excited to see the final version!
