### ISSUE TITLE
Listen to schema changes

### ISSUE THREAD

**Issue by marcelobarreto** [supabase/realtime#149]
# Feature request

I'd like to know when the schema was modified (also, get the current version of it). So I could have some actions based on the data.

## Is your feature request related to a problem? Please describe.

No

## Describe the solution you'd like

I'd like to work on this one, but I confess that need some guidance. And also, I would like to design the solution as a team.
PS.: I'm studying Elixir, but I think this might be the [file](https://github.com/supabase/realtime/blob/master/server/lib/realtime/subscribers_notification.ex#L39) I'll need to change/add some stuff

**Comment by w3b6x9** [comment]
@marcelobarreto thanks for creating the issue and welcome to Elixir!

Just to be clear, are you requesting listening to changes for when schema itself is altered (e.g. `ALTER SCHEMA public RENAME TO test`) and not https://github.com/supabase/realtime/blob/master/server/lib/realtime/subscribers_notification.ex#L55?

**Comment by marcelobarreto** [comment]
Hey @w3b6x9 I was thinking about when we add/remove/change columns for example.

**Comment by kiwicopple** [comment]
Hey @marcelobarreto - i don't know if this is possible since this server just listens to the postgres `WAL`

postgres stores the schema inside internal tables - https://www.postgresql.org/docs/current/catalogs.html

1. Postgres doesn't register changes to these tables into a the `WAL` (needs verification)
2. it seems dangerous - like this would somehow have some infinite loop, or some unknown side effect.

I don't know enough about the internals of the catalogs+WAL to know if this is even possible, but you're welcome to try to satisfy a curiosity :). you'd need to follow [these steps](https://github.com/supabase/realtime#server) but use the [pg_tables](https://www.postgresql.org/docs/current/view-pg-tables.html) instead of your own database tables

**Comment by marcelobarreto** [comment]
thanks @kiwicopple, I'll give it a try.

**Comment by kiwicopple** [comment]
Hey @marcelobarreto - I'll close this for now, but if you make progress feel free to update and I can reopen
