### ISSUE TITLE
Is it possible to subscribe to updates on specific columns ?

### ISSUE THREAD

**Issue by AaronNGray** [supabase/realtime#164]
### Discussed in https://github.com/supabase/supabase/discussions/2039

<div type='discussions-op-text'>

<sup>Originally posted by **AaronNGray** June 22, 2021</sup>
Is it possible to subscribe to updates on specific columns ?

I.e. to generate a clause :- 

```CREATE TRIGGER name AFTER UPDATE OF column ...```
</div>

**Comment by w3b6x9** [comment]
@AaronNGray it is possible but we don't have a performant way of doing this at the moment. In order to do this as it currently exists, we would need to broadcast a message for every single column in a db change. We're actually already doing something quite similar for users to be able to match against a specific value in a column (e.g. `realtime:public:users.id=eq.2`), which means sending excess messages causing memory bloat to the Realtime server.

We've been exploring a few ways of improving Realtime (replication and websocket broadcasting) and have discussed in the past, and continue to explore, better ways to subscribe to the exact changes that you want (be it on a schema, table, column, matching value, etc.).

I'm going to leave this issue open so that we can further explore potential solutions.

**Comment by AaronNGray** [comment]
Sorry I have move to using Vercel / Next.js / React,js + Vesper / TypeORM stack now and doing subscriptions via pubsub at GraphQL resolvers.
