### ISSUE TITLE
guide for dropping this into an existing phoenix app?

### ISSUE THREAD

**Issue by cultofmetatron** [supabase/realtime#44]
I'm currently building an mvp using phoenix. subscribing to database changes is an issue I've been looking into and I was researching debezium for that purpose. This looks like a much better fit however. Are there any existing docs on how to integrate this into an existing phoenix app?

Also, do you guys have clients for ios/android?

**Comment by kiwicopple** [comment]
Thanks for checking it out. One reason we developed it was because Debezium didn't fit our needs too.

This repo serves more as a "standalone" server, but if you want to drop the functionality into your own phoenix app we suggest you check out [Cainophile's library](https://github.com/cainophile/cainophile) which gave us a lot of the baseline functionality. It can be installed as a hex module and it's an amazing piece of work.

Alternatively, you can run this side-by-side with your phoenix app - you will need to install it on a new server (detailed docs coming soon with instructions on how to do this), but it's then simply a matter of "pointing it" towards your database and then connecting with a client library.

> Also, do you guys have clients for ios/android?

Not yet, but we're tracking this here: https://github.com/supabase/realtime/issues/44
