### ISSUE TITLE
Database disk usage issue?

### ISSUE THREAD

**Issue by retendo** [supabase/realtime#61]
I connect the supabase/realtime server to a managed postgres db on DigitalOcean.
There seems to be an issue with disk usage, which is related to the realtime server, as in: If I boot up the realtime server, the db's disk usage will at some point begin to start rising. After reaching around 96% it will drop down, but it will rise again shortly after. If I shut it down, then the disk usage will drop back down to around 20% and stay there.

<img width="793" alt="Screenshot 2020-08-04 at 13 59 17" src="https://user-images.githubusercontent.com/1295043/89291747-613d5980-d65b-11ea-91a6-94e1951de985.png">

I can't tell if it has significant implications on database usability/performance, as I'm not yet using it in production, but it is annoying as I always get warnings from DigitalOcean like these:

> Your database XXXXX is low on resources. Hello, Your postgres service, XXXXX, is running low on disk. If your service runs out of disk space, writes will be denied and other functionality could be rendered unavailable. Either delete unnecessary data or upgrade to a larger plan to avoid service outage.

**Comment by kiwicopple** [comment]
You're becoming a real power user @retendo , thanks for digging up all these niche issues. We saw this once, but it was due to a rogue query. Can you try a few things?

- Run `pg_stat_activity` and check if there are a few long-running queries?
- Confirm if you are dumping a large amount of updates/inserts each day? (which will trigger a huge amount of changes to the WAL)
- check the [size of the WAL](https://dba.stackexchange.com/questions/192564/is-there-a-query-to-check-the-current-wal-size-in-postgresql)
- Send through the details of the active replication slots: https://www.postgresql.org/docs/current/view-pg-replication-slots.html

If you also use slack, I can add you to our internal slack and we can debug together. Send me an email if you want a slack invite: copple[at]supabase[dot]io

**Comment by kiwicopple** [comment]
It might also be worth disconnecting everything from the database (including Realtime) and see if this is still happening, to help isolated the root cause

**Comment by retendo** [comment]
> It might also be worth disconnecting everything from the database (including Realtime) and see if this is still happening, to help isolated the root cause

I already did that, and it was only happening when realtime server was connected. I have 3 services running and I tried almost every combination. It's only happening when realtime is connected, no matter which other services are connected or not.

> If you also use slack, I can add you to our internal slack and we can debug together.

Sure, I'll drop you a mail.

**Comment by soedirgo** [comment]
Copying my message from Slack:

> Hey @retendo, can you tell me how you set up Realtime with DO’s managed Postgres? IIUC you don’t have superuser access in managed Postgres [0], which means you can’t do `ALTER SYSTEM` and `CREATE PUBLICATION`, which means Realtime doesn’t work with it [1]
> [0] https://www.digitalocean.com/docs/databases/postgresql/#postgresql-limits
> [1] https://supabase.io/docs/realtime/about#setting-up-replication

**Comment by soedirgo** [comment]
I was able to replicate this on both DO and AWS. From AWS:

<img width="439" alt="Screen Shot 2020-08-16 at 7 55 17 PM" src="https://user-images.githubusercontent.com/31685197/90333695-8f774d80-dffa-11ea-95ec-a3cd1c06ee72.png">

Unlike DO, the disk space doesn't get freed once it's full. Looking at another monitor, it seems like transaction log is the culprit:

<img width="442" alt="Screen Shot 2020-08-16 at 7 55 04 PM" src="https://user-images.githubusercontent.com/31685197/90333728-b5045700-dffa-11ea-94d1-a8e8bb10f4c9.png">

This was an idle Postgres database (aside from a few queries for sanity check). I'm not sure what filled up the transaction log, but I saw these queries keep happening on DO:

<img width="1167" alt="Screen Shot 2020-08-16 at 8 18 41 PM" src="https://user-images.githubusercontent.com/31685197/90334120-c8fd8800-dffd-11ea-8be4-4d2fa9b38ff5.png">

So assuming it's some managed DB services that make these transactions (because there's no such problem AFAIK in Supabase Postgres), it could be that unvacuumed WAL blows up the disk space.

Not sure how to fix this yet.

**Comment by kiwicopple** [comment]
Update of root cause, from [SO](https://stackoverflow.com/questions/60710947/postgres-replication-slot-from-kafka-connect-is-filling-up):

> The most common reason why the PostgreSQL WAL backlogs is because the connector is monitoring a database or a subset of tables from your database change much more infrequent compared to the other tables or databases in your environment and therefore the connector isn't acknowledging the LSNs frequent enough to avoid the WAL backlog.

This seems to be caused on DO and AWS because they have their own background processes running.

- Slot 1 - DO replication gets triggered on every change
- Slot 2 - Supabase replication only gets triggered if a specified table gets changed

Because Supabase is only receiving infrequent events, it never has a chance to "acknowledge" the latest `lsn`. When some new data is inserted though, the acknowledgement goes through and the storage is cleared:

![reduce_lag](https://user-images.githubusercontent.com/10214025/93744302-2f408080-fc24-11ea-876c-3c1662ced777.gif)

**Comment by kiwicopple** [comment]
Workaround while we solve this:

*1. Create a table in your database called "heartbeat"*

```sql
create table public.heartbeat (
  updated_at   timestamp
);
```

*2. Add this table to the publication

```sql
CREATE PUBLICATION supabase_realtime FOR ALL TABLES; 

-- if you can't do this on your server, try create it for just the table:
CREATE PUBLICATION supabase_realtime FOR TABLE heartbeat
```


*3. Every so often, update this table*

```sql
update heartbeat set updated_at = now(); 
```

If you trigger `3` every minute or so, the database will clear the data stored for the slot.

We will add a function to this server where we can send an acknowledgement every few seconds without this workaround

**Comment by AshaBhasker** [comment]
HI there i am still facing this issue with supabase/postgres:14.1.0.21 its consuming disk space without any usease.

**Comment by w3b6x9** [comment]
> HI there i am still facing this issue with supabase/postgres:14.1.0.21 its consuming disk space without any usease.

@AshaBhasker are you using Realtime at all?

**Comment by AshaBhasker** [comment]
@w3b6x9 No, I am not using Realtime

**Comment by bhasker1980** [comment]
I configured Supabase on digitalocean Droplet using this documentation:
https://www.vultr.com/docs/how-to-install-supabase-on-ubuntu-20-04/
after 1week I saw that all the disk space is consumed. I saw  var/log/postgresql/postgresql.csv  file consumed all disk space. So i disabled the logging. and re-configure the supabase. Now this file size is not increasing but server disk space is still consumed. 
Please help me fix this issue.

**Comment by jsbrain** [comment]
@w3b6x9 I'm experiencing the same issue with `supabase/postgres:14.1.0.21`.
Did you fix it?

**Comment by kiwicopple** [comment]
you can disable logging in the postgres config by setting the `log_level = fatal`
