### ISSUE TITLE
Large inserts choke micro instances

### ISSUE THREAD

**Issue by awalias** [supabase/realtime#81]
inserting 1 million rows at the same time cause excessive CPU usage for an extended period afterwards, along with ~50% RAM:

![image](https://user-images.githubusercontent.com/458736/100217970-0b185d00-2f4f-11eb-9803-df09d77a9316.png)

test code here: https://raw.githubusercontent.com/supabase/benchmarks/feat/firestore-benchmarks/db/migrations/20201124141199_read_data.sql 

ruled out COPY being the issue since the following snippet also results in the same behaviour:

```sql
do $$
begin
for r in 1..1000000 loop
insert into public.read(id, slug) values(r, r);
end loop;
end;
$$;
```

Restarting the service (process) does not resolve the issue

**Comment by kiwicopple** [comment]
🤔 Move to rust? 

Let me think how we can solve this - the plan was to add workflows to this server, which will only make it slower. At the moment we are parsing every event, then looping through every column, so it is a lot to get through. Realistically a user doesn't need all of these notifications and should be adding [Event Filters](https://github.com/supabase/realtime/pull/76) to included only what they really need

**Comment by awalias** [comment]
I guess the sensible solution for now is to temporarily disable the `supabase_realtime` publication temporarily for large dumps like this

**Comment by soedirgo** [comment]
I'm seeing 2 problems:
- Decoding takes a *really* long time. Locally, decoding an `INSERT` of 1 million rows takes more than an hour just to decode. On the other hand, for a subscription with a second DB, decoding and applying takes *5 seconds*.
- After decoding, `SubscribersNotification` crashes on `handle_call/3`. Maybe because of the huge size of the arguments, since messages are sent per transaction, i.e. all 1 million decoded messages at once.

I feel like a Rust NIF that sends messages one by one might make sense here...

**Comment by kiwicopple** [comment]
> Decoding takes a really long time. 

Interesting. Is there any low-hanging fruit here? Is it the actual decoding or the parsing into various channels?

Otherwise if you can do a quick POC of the NIF, it  might be good to compare

**Comment by soedirgo** [comment]
Just decoding, it errored out when `notify`ing SubscribersNotification.

> if you can do a quick POC of the NIF

👍
